# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de74d3c6cfab5f9ccad061b2b1d82e46"
name = "OTB Planner App"
application_url = "https://example.com"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["http://localhost:3457/callback"]